name: General Question / Other
description: Ask a question or report something else
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a general question, please check if a similar question has already been asked.
        For build-related questions, please also check the project documentation and README.
        
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: A clear and concise description of what you want to know or what you're trying to accomplish.
      placeholder: I would like to know [...]
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help us understand your question better.
      placeholder: |
        - What are you trying to build or accomplish?
        - What have you already tried?
        - Any relevant environment details?
        
  - type: textarea
    id: environment
    attributes:
      label: Environment information (if applicable)
      description: |
        If your question is environment-specific, please provide details:
        - OS and version
        - Docker version (if applicable)
        - Build tool versions
        - Any other relevant environment details
      placeholder: |
        OS: Ubuntu 20.04
        Docker: 20.10.7
        Build system: CMake 3.16.3
        Other: ...
        
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant.
      
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0